#!/bin/sh

CMD=$(basename "$0")
ACTION=$1

if [ "$ACTION" = "usage" ]; then
	echo "  hide [TERM...]"
	echo "    Hide tasks containing ANY of the listed TERM(s):"
	echo "    $TODO_SH $CMD +foo bar"
	echo ""

	exit
fi

shift 1
ARGS=$*

if [ -z "$ARGS" ]; then
	"$TODO_FULL_SH" list
	exit
fi

TERMS=$(echo "$ARGS" | sed 's/ \+/ -/')
"$TODO_FULL_SH" list -$TERMS
